Front-End/bibim/vite/src/views/workdata/components/FileCardView.jsx
Front-End/bibim/vite/src/views/workdata/components/FileTable.jsx

<br/>
feat/workspace_front -> dev
<br/>
- **AS-IS**
- 자료실 미리보기 기능 추가
- 자료실 정보 모달에서 사진 이미지 추가
- **TO-BE**
<br />
<br/>
<br/>
<br/>

feat: 자료실 미리보기 및 이미지 추가

---

Front-End/bibim/vite/src/api/tag.js
Front-End/bibim/vite/src/views/schedule/components/TagCreateModal.jsx
Front-End/bibim/vite/src/views/schedule/components/TagEditModal.jsx
Front-End/bibim/vite/src/views/schedule/index.jsx

<br/>
feat/schedule/tag-modal -> dev
<br/>
- **AS-IS**
태그 생성 모달 만들었습니다. 대분류/중분류/소분류 태그 생성 후 DB 확인했고, 중복시 생성 안되는 것도 확인했습니다.
- **TO-BE**
<br />
태그 수정 모달이 만들어져있지만 아직 테스트가 안되어있습니다. 테스트 후 새로 pr 올리겠습니다.
<br/>
<br/>
<br/>

feat: schedule/tag modal

---

Front-End/bibim/vite/src/ui-component/cards/MainCard.jsx
Front-End/bibim/vite/src/views/dm/components/ChatLoading.jsx
Front-End/bibim/vite/src/views/dm/index.jsx
Front-End/bibim/vite/src/views/pages/auth-forms/AuthRegister.jsx
Front-End/bibim/vite/src/views/pages/authentication/AuthCardWrapper.jsx

<br/>
<br/>
- **AS-IS**
- 회원가입 폼 CSS 변경 
- DM 채팅 로딩화면 추가 
- **TO-BE**
<br />
<br/>
<br/>
<br/>

feat: 회원가입 폼 및 dm 채팅 로딩 추가

---

Back-End/src/main/java/net/scit/backend/workdata/service/impl/WorkdataServiceImpl.java

<br/>
workdata-refactor -> dev
<br/>
- **AS-IS**
자료실 전체조회 시 파일 관련 정보가 없어 상세조회를 땡겨옴으로써 2번 조회해야 했음 -> 전체조회에 코드 추가하여 모든 자료실의 파일 정보 조회 가능
- **TO-BE**
<br />
<br/>
<br/>
<br/>

refactor: 자료실 전체조회 시 파일 이름, url 등 출력

---

Back-End/src/main/java/net/scit/backend/config/SecurityConfig.java
Back-End/src/main/java/net/scit/backend/member/controller/MemberController.java
Back-End/src/main/java/net/scit/backend/member/dto/WorkspaceChannelLoginStatusDTO.java
Back-End/src/main/java/net/scit/backend/member/service/impl/MemberServiceImpl.java
Back-End/src/main/java/net/scit/backend/workspace/controller/WorkspaceChannelController.java
Back-End/src/main/java/net/scit/backend/workspace/controller/WorkspaceController.java
Back-End/src/main/java/net/scit/backend/workspace/repository/WorkspaceMemberRepository.java
Back-End/src/main/java/net/scit/backend/workspace/service/WorkspaceChannelService.java
Back-End/src/main/java/net/scit/backend/workspace/service/WorkspaceService.java
Back-End/src/main/java/net/scit/backend/workspace/service/impl/WorkspaceChannelServiceImpl.java
Back-End/src/main/java/net/scit/backend/workspace/service/impl/WorkspaceServiceImpl.java

<br/>
jasper-qc -> dev
<br/>
- **AS-IS**
1. 알림 url 관련 securityConfig 내용 추가
2. 워크스페이스 채널 내 팀원 접속현황 조회 기능 추가(기존 접속현황과 DTO 꼬임으로 인한 새로운 DTO 생성-workspaceChannelLoginStatusDTO)
<br/>
<br/>
<br/>

feat: 워크스페이스 채널 내 팀원 접속현황 조회

---

Front-End/bibim/vite/src/api/schedule.js
Front-End/bibim/vite/src/views/schedule/components/GanttChart.jsx
Front-End/bibim/vite/src/views/schedule/components/ScheduleCreateModal.jsx
Front-End/bibim/vite/src/views/schedule/components/ScheduleDetailModal.jsx
Front-End/bibim/vite/src/views/schedule/components/ScheduleEditModal.jsx
Front-End/bibim/vite/src/views/schedule/components/TagCreateModal.jsx
Front-End/bibim/vite/src/views/schedule/index.jsx

<br/>
feat/schedule_noti  -> dev
<br/>
- **AS-IS**
- 스케줄 생성시 대분류, 중분류, 소분류 태그 가져오기 수정
- 스케줄 태그 생성 모달 수정
- 스케줄 호출 관련 api (캘린더, 간트 / 칸반보드) 2개로 분리
- 스케줄 간트차트뷰일시 툴팁 수정 (상태값 변경)
- 스케줄 상세 모달에서 스케줄 상태 값 추가  
- **TO-BE**
<br />
<br/>
<br/>
<br/>

feat: 일정관리 내 태그 관련 기능 추가

---

Back-End/src/main/java/net/scit/backend/channel/DTO/MessageDTO.java
Back-End/src/main/java/net/scit/backend/channel/entity/MessageEntity.java
Back-End/src/main/java/net/scit/backend/channel/service/impl/ChannelServiceImpl.java
Front-End/bibim/vite/src/views/dm/index.jsx
Front-End/bibim/vite/src/views/ws-channel/ChatComponent.jsx

<br/>
fix/channel-file-download -> dev
<br/>
- **AS-IS**
파일 올릴시 파일 다운로드가 정상적으로 되도록 처리 하였습니다.
<br />
<br/>

feat: 프론트 채널 및 dm 파일 다운로드 수정

---

Back-End/src/main/java/net/scit/backend/member/listener/MemberEventListener.java
Back-End/src/main/java/net/scit/backend/schedule/listener/ScheduleEventListener.java
Back-End/src/main/java/net/scit/backend/workdata/listener/WorkdataEventListener.java
Back-End/src/main/java/net/scit/backend/workspace/listener/WorkspaceChannelEventListener.java
Back-End/src/main/java/net/scit/backend/workspace/listener/WorkspaceEventListener.java

<br/>
jasper-2th-refactor -> dev
<br/>
- **AS-IS**
SSE 구독 및 구독해제 관련 SSE를 Map 기반으로 타입 변경함에 따른 전체 이벤트리스너 변경
- **TO-BE**
<br />
<br/>
<br/>
<br/>

refactor: SSE 로직 변경에 따른 Map 기반 전체 이벤트 리스너 변경

---

Back-End/src/main/java/net/scit/backend/channel/service/impl/ChannelServiceImpl.java
Back-End/src/main/java/net/scit/backend/dm/service/impl/DmServiceImpl.java
Front-End/bibim/vite/src/views/dm/index.jsx
Front-End/bibim/vite/src/views/ws-channel/ChatComponent.css
Front-End/bibim/vite/src/views/ws-channel/ChatComponent.jsx

<br/>
fix/channel-time-bug -> dev
<br/>
- **AS-IS**
수정:
1. 시간 css 위치 수정
2. 시간이 바로 뜨지 않는 경우 수정
3. 내가 보낸 dm 이 두번 뜨는 것을 수정
4. dm 과 채널에서 아무 파일이나 업로드 가능하도록 변경
<br />
<br/>

fix: 프론트 채널 오류 해결

---

Front-End/bibim/vite/src/api/workdata.js
Front-End/bibim/vite/src/views/dm/index.jsx
Front-End/bibim/vite/src/views/workdata/index.jsx

<br/>
feat/front_connect -> dev
<br/>
- **AS-IS**
- 자료실 프론트엔드 코드 수정
- dm 채팅 내역 로딩 상태 추가 
- **TO-BE**
<br />
<br/>
<br/>
<br/>

feat: 자료실 등, 프론트엔드 여러기능 추가

---

.gitignore
Front-End/bibim/vite/.env
Front-End/bibim/vite/.gitignore
Front-End/bibim/vite/src/api/translate.js
Front-End/bibim/vite/src/views/dm/index.jsx

<br/>
feat/front_test -> dev
<br/>
- **AS-IS**
- env파일 git 추적 삭제
- 번역함수 추가
- **TO-BE**
<br />
<br/>
<br/>
<br/>

feat: env ignore추가 및 번역함수

---

Back-End/src/main/java/net/scit/backend/workspace/controller/WorkspaceChannelController.java
Back-End/src/main/java/net/scit/backend/workspace/dto/ChannelDTO.java
Back-End/src/main/java/net/scit/backend/workspace/dto/ChannelUpdateRequest.java
Back-End/src/main/java/net/scit/backend/workspace/repository/WorkspaceChannelRepository.java
Back-End/src/main/java/net/scit/backend/workspace/service/WorkspaceChannelService.java
Back-End/src/main/java/net/scit/backend/workspace/service/impl/WorkspaceChannelServiceImpl.java

추가: 해당 워크스페이스로 채널 리스트를 전부 조회하는 api를 만들었습니다.
<br/>
feat/channel-list-request-> dev
<br/>
- **AS-IS**
워크스페이스 id로 채널 리스트 전부 조회 추가
<br />
<br/>

feat: 워크스페이스 id로 채널 리스트 전부 조회

---

Back-End/src/main/java/net/scit/backend/workspace/controller/WorkspaceChannelController.java
Front-End/bibim/vite/src/api/channel.js
Front-End/bibim/vite/src/views/ws-channel/components/ChatComponent.jsx
Front-End/bibim/vite/src/views/ws-channel/index.jsx

<br/>
feat/channel_front -> dev
<br/>
- **AS-IS**
- 채널 폴더 구조 수정
- 채널 api 추가
- 채널 선택 drawer 추가
- 채널 메뉴 선택시 각 워크스페이스 별 기본 채널 입장 설정
- **TO-BE**
<br />
<br/>
<br/>
<br/>

feat: 채널 선택 drawer 및 기본 채널 입장 설정

---

Front-End/bibim/vite/src/layout/MainLayout/Header/NotificationSection/index.jsx

<br/>
<br/>
- **AS-IS**
페이지 내 알림 아이콘 우상단에 실시간으로 개수 표시(더 수정하려고 했으나 rebase 쓰는 것보단 일단 pull 받고 시작하기 위해)
- **TO-BE**
그 외 알림 프론트 구현 예정
<br />
<br/>
<br/>
<br/>

feat: 읽지 않은 알림 개수 아이콘 우상단 표시

---

Back-End/src/main/java/net/scit/backend/notification/controller/NotificationController.java
Back-End/src/main/java/net/scit/backend/notification/repository/NotificationRepository.java
Back-End/src/main/java/net/scit/backend/notification/service/NotificationService.java
Back-End/src/main/java/net/scit/backend/notification/service/impl/NotificationServiceImpl.java
Front-End/bibim/vite/src/layout/MainLayout/Header/NotificationSection/index.jsx

<br/>
feat/notification-icon -> dev
<br/>
- **AS-IS**
1. 페이징 기반 알림 무한 스크롤 기반에서 기존의 리스트 형식으로의 반환
2. 프론트엔드에서의 호출 완료
3. 
- **TO-BE**
아직 할일이 산더미라 따로 기술하지 않고 pr로 승부 보겠음 
<br />
<br/>
<br/>
<br/>

refactor: 알림 페이지 무한 스크롤 기능에서 기존 리스트 형식으로의 변환

---

Front-End/bibim/vite/src/views/ws-channel/components/ChatComponent.jsx

수정: use이펙트의 내용을 수정하여 속도를 조금 더 높였습니다
<br/>
Fix/channel optimazer -> dev
<br/>
- **AS-IS**
수정: use이펙트의 내용을 수정하여 속도를 조금 더 높였습니다
<br />
<br/>

fix: 채널 로딩 속도 개선

---

Back-End/src/main/java/net/scit/backend/workspace/controller/WorkspaceChannelController.java
Back-End/src/main/java/net/scit/backend/workspace/repository/WorkspaceChannelRepository.java
Back-End/src/main/java/net/scit/backend/workspace/service/WorkspaceChannelService.java
Back-End/src/main/java/net/scit/backend/workspace/service/impl/WorkspaceChannelServiceImpl.java

<br/>
fix/creat-channel -> dev
<br/>
- **AS-IS**
채널 생성시 생성한 ID와 채널 이름 반환
<br />
<br/>

fix: 채널 생성시 생성한 ID와 채널 이름 반환

---

Front-End/bibim/vite/src/layout/MainLayout/Header/NotificationSection/index.jsx
Front-End/bibim/vite/src/views/dm/index.jsx
Front-End/bibim/vite/src/views/ws-channel/components/ChannelCreateModal.jsx
Front-End/bibim/vite/src/views/ws-channel/components/ChannelEditModal.jsx
Front-End/bibim/vite/src/views/ws-channel/components/ChatComponent.css
Front-End/bibim/vite/src/views/ws-channel/components/ChatComponent.jsx

<br/>
feat/channel_detail -> dev
<br/>
- **AS-IS**
- 채널 채팅 번역기능 추가
- 알림버튼 커서 포인터 추가
- 불필요 컴퍼넌트 및 코드 제거
- 채널 CSS 추가
- 채널 생성 모달 코드 수정 
- **TO-BE**
<br />
<br/>
<br/>
<br/>

feat: 채널 번역 등 기능 추가

---

Back-End/src/main/java/net/scit/backend/notification/controller/NotificationController.java
Back-End/src/main/java/net/scit/backend/notification/service/impl/NotificationServiceImpl.java
Front-End/bibim/vite/src/layout/MainLayout/Header/NotificationSection/NotificationList.jsx
Front-End/bibim/vite/src/layout/MainLayout/Header/NotificationSection/index.jsx

<br/>
notification-frontend -> dev
<br/>
- **AS-IS**
1. 알림 삭제 리팩토링
2. 시간 출력방식 리팩토링(24시간 경과 후 해당일로부터 며칠 지났는지를 기준으로 n일 전으로 표현)
- **TO-BE**
남은 알림 프론트 구현 ㅠ
<br />
<br/>
<br/>
<br/>

refactor: 알림 삭제, 시간 출력방식 리팩토링 

---

Front-End/bibim/vite/src/views/ws-channel/index.jsx

<br/>
<br/>
- **AS-IS**
- 채널 페이지 오류 수정 
- **TO-BE**
<br />
<br/>
<br/>
<br/>

refactor: 채널 페이지 오류 수정

---

Front-End/bibim/vite/src/views/workdata/components/FileTable.jsx

<br/>
ex) fix/workdata-photo -> dev
<br/>
- **AS-IS**
- 자료실 사진 미리보기가 이제 깜빡이지 않습니다.
- **TO-BE**
<br />
<br/>
<br/>
<br/>

fix:workdata-photo 자료실 사진 미리보기 깜빡임 문제 수정

---

Back-End/src/main/java/net/scit/backend/schedule/dto/UpdateLargeTagDTO.java
Back-End/src/main/java/net/scit/backend/schedule/dto/UpdateMediumTagDTO.java
Back-End/src/main/java/net/scit/backend/schedule/dto/UpdateSmallTagDTO.java
Back-End/src/main/java/net/scit/backend/schedule/service/impl/ScheduleServiceImpl.java
Front-End/bibim/vite/src/api/tag.js
Front-End/bibim/vite/src/views/schedule/components/TagEditModal.jsx

<br/>
<br/>
- **AS-IS**
태그 수정 모달창 기능 구현 했습니다. 태그 수정 및 삭제 가능합니다.
- **TO-BE**
<br />
<br/>
<br/>
<br/>

refactor: schedule/tag-update-modal

---

Front-End/bibim/vite/src/menu-items/utilities.js
Front-End/bibim/vite/src/ui-component/cards/MainCard4.jsx
Front-End/bibim/vite/src/views/schedule/components/Calendar.jsx
Front-End/bibim/vite/src/views/schedule/components/GanttChart.jsx
Front-End/bibim/vite/src/views/schedule/components/KanbanBoard.jsx
Front-End/bibim/vite/src/views/schedule/components/ScheduleCreateModal.jsx
Front-End/bibim/vite/src/views/schedule/components/ScheduleDetailModal.jsx
Front-End/bibim/vite/src/views/schedule/index.jsx

<br/>
feat/schedule_front -> dev
<br/>
- **AS-IS**
- 스케줄 상세 모달 불러올 때, 스케줄 생성 모달 생성할때, 스케줄 상세모달에서 삭제할 때, 로딩 및 스낵바 추가
- 스케줄 페이지 디자인 및 구조 살짝 수정
- 간트차트에서 상태반영
- 메인에서 일정수정버튼 삭제
- 스케줄 (상세 모달) 삭제기능 추가
- 스케줄 생성 및 삭제시 바로 반영되도록 추가
- 스케줄 관련 라우터 및 메뉴 수정
- **TO-BE**
<br />
<br/>
<br/>
<br/>

feat: 일정관리 관련 구조변경 및  여러 기능 추가

---

Front-End/bibim/vite/src/routes/AuthenticationRoutes.jsx
Front-End/bibim/vite/src/views/landing/components/LandingHeader.jsx
Front-End/bibim/vite/src/views/landing/index.jsx
Front-End/bibim/vite/src/views/landing/landing1.jsx
Front-End/bibim/vite/src/views/landing/landing3.jsx

<br/>
ex) feat/landing-page)-> dev
<br/>
- **AS-IS**
- 랜딩페이지 샘플을 몇가지 만들었습니다. 사이드바의 랜딩페이지를 통해서 접근한 뒤, 1과 3은 최하단에 있는 버튼을 통해 접근 가능합니다. 
- **TO-BE**
- 사이트 완성된 뒤에 사이트 스크린샷 추가 필요.
- 디자인 디테일 수정 필요(컬러 등)
<br />
<br/>
<br/>
<br/>

feat:landing-page

---

Back-End/src/main/java/net/scit/backend/config/SecurityConfig.java
Back-End/src/main/java/net/scit/backend/jwt/JwtTokenProvider.java
Back-End/src/main/java/net/scit/backend/member/event/MemberEvent.java
Back-End/src/main/java/net/scit/backend/member/listener/MemberEventListener.java
Back-End/src/main/java/net/scit/backend/notification/controller/NotificationController.java
Back-End/src/main/java/net/scit/backend/notification/service/impl/NotificationServiceImpl.java
Back-End/src/main/java/net/scit/backend/schedule/event/ScheduleEvent.java
Back-End/src/main/java/net/scit/backend/schedule/listener/ScheduleEventListener.java
Back-End/src/main/java/net/scit/backend/workdata/event/WorkdataEvent.java
Back-End/src/main/java/net/scit/backend/workdata/listener/WorkdataEventListener.java
Back-End/src/main/java/net/scit/backend/workspace/event/WorkspaceChannelEvent.java
Back-End/src/main/java/net/scit/backend/workspace/event/WorkspaceEvent.java
Back-End/src/main/java/net/scit/backend/workspace/listener/WorkspaceChannelEventListener.java
Back-End/src/main/java/net/scit/backend/workspace/listener/WorkspaceEventListener.java
Front-End/bibim/vite/src/layout/MainLayout/Header/NotificationSection/NotificationList.jsx
Front-End/bibim/vite/src/layout/MainLayout/Header/NotificationSection/index.jsx

<br/>
notification-frontend-done -> dev
<br/>
- **AS-IS**
1. 알림 이름을 키워드로 압축 + 향상된 case문 사용
2. 알림 리다이렉트 주소 구현 완료 및 일부 테스트 성공(현재 자료실 url 에러 떠서 수정해야 함)
3. 페이지 새로고침 없이 찐 실시간 알림 받아오기 리팩토링
4.알림 삭제 오류 관련 리팩토링 완료 but 사소한 에러 있음
- **TO-BE**
1. url 매핑 확실하게 
2. 기타 리팩토링
<br />
<br/>
<br/>
<br/>

refactor: 알림 프론트 1차 완성

---

Back-End/src/main/java/net/scit/backend/notification/repository/NotificationRepository.java
Back-End/src/main/java/net/scit/backend/notification/service/NotificationCleanupService.java

<br/>
notification-url-refactoring -> dev
<br/>
- **AS-IS**
DB 최적화를 위해 매주 일요일 자정, 읽은 알림 중에서 7일이 지난 알림은 자동으로 삭제하도록 스케줄링 처리를 함
- **TO-BE**
<br />
<br/>
<br/>
<br/>

feat: 일주일 지난 알림 자동 삭제 구현

---

Front-End/bibim/vite/src/menu-items/utilities.js
Front-End/bibim/vite/src/routes/AuthenticationRoutes.jsx
Front-End/bibim/vite/src/routes/LandingRoutes.jsx
Front-End/bibim/vite/src/routes/MainRoutes.jsx
Front-End/bibim/vite/src/routes/index.jsx

<br/>
<br/>
- **AS-IS**
- **TO-BE**
<br />
<br/>
<br/>
<br/>

feat: 라우터 수정 및 랜딩 페이지 바로 렌더링

---

Front-End/bibim/vite/src/views/dm/index.jsx

<br/>
<br/>
- **AS-IS**
-  dm 주소 수정 (/api까지)
- **TO-BE**
<br />
<br/>
<br/>
<br/>

feat: dm 주소 수정

---

Back-End/src/main/java/net/scit/backend/schedule/service/impl/ScheduleServiceImpl.java

특정 스케줄 정보를 가져올 때 스케줄 담당자가 아닌 본인으로 가져오은 것을 수정했습니다.
<br/>
refactor/get-schedule -> dev
<br/>
- **AS-IS**
특정 스케줄 정보를 가져올 때 스케줄 담당자가 아닌 본인으로 가져오는 것을 수정했습니다.
- **TO-BE**
<br />
<br/>
<br/>
<br/>

 refactor:get-schedule

---

Front-End/bibim/vite/src/api/mypage.js
Front-End/bibim/vite/src/views/landing/index.jsx
Front-End/bibim/vite/src/views/mypage/component/MyCalendar.jsx
Front-End/bibim/vite/src/views/mypage/component/MyGanttChart.jsx
Front-End/bibim/vite/src/views/mypage/component/MyScheduleDetailModal.jsx
Front-End/bibim/vite/src/views/mypage/component/MyScheduleEditModal.jsx
Front-End/bibim/vite/src/views/mypage/component/mySchedule.jsx
Front-End/bibim/vite/src/views/mypage/index.jsx
Front-End/bibim/vite/src/views/schedule/components/Calendar.jsx
Front-End/bibim/vite/src/views/schedule/components/GanttChart.jsx

<br/>
ex) feat/my-schedule -> dev
<br/>
- **AS-IS**
- 랜딩페이지 문구 수정, 무지개 효과 추가
- 마이페이지 스케줄 일정 없을 시 일정 없음 표시되도록
- 전체 캘린더, 전체 간트차트 박스 수정
- 간트차트 아이콘 90도 돌림 
- **TO-BE**
- 칸반보드 기능 완성시 추가 수정 필요 (현재 담당자 지정이 불가능해 마이페이지에서 api 테스트 불가.
<br />
<br/>
<br/>
<br/>

feat:my-schedule 스케줄 css 

---

Back-End/src/main/java/net/scit/backend/channel/DTO/MessageDTO.java
Back-End/src/main/java/net/scit/backend/channel/entity/MessageEntity.java
Back-End/src/main/java/net/scit/backend/channel/service/impl/ChannelServiceImpl.java
Back-End/src/main/java/net/scit/backend/dm/DTO/DmMessageDTO.java
Back-End/src/main/java/net/scit/backend/dm/service/impl/DmServiceImpl.java
Back-End/src/main/java/net/scit/backend/workspace/repository/WorkspaceMemberRepository.java
Back-End/src/main/java/net/scit/backend/workspace/service/impl/WorkspaceServiceImpl.java
Front-End/bibim/vite/src/views/dm/index.jsx
Front-End/bibim/vite/src/views/ws-channel/components/ChatComponent.jsx

<br/>
Fix/nickname channel dm -> dev
<br/>
- **AS-IS**
수정: 현재 프로필 사진과 닉네임이 제대로 반영 되지 않을 것을 수정 하였습니다.
- **TO-BE**
예정: 프로필 사진 CSS 수정 예정
<br />
<br/>

fix: 채널, dm 프로필 및 닉네임 수정

---

Front-End/bibim/vite/src/layout/MainLayout/Sidebar/index.jsx
Front-End/bibim/vite/src/views/mypage/component/DeleteStatusModal.jsx
Front-End/bibim/vite/src/views/mypage/component/FileDetailModal.jsx
Front-End/bibim/vite/src/views/mypage/component/MyWorkData.jsx
Front-End/bibim/vite/src/views/mypage/component/mySchedule.jsx
Front-End/bibim/vite/src/views/mypage/index.jsx
Front-End/bibim/vite/src/views/schedule/index.jsx

<br/>
ex) feat/my workdata -> dev
<br/>
- **AS-IS**
- 마이페이지에 내 자료실을 연결했습니다.
- 간트 차트 아이콘을 90도로 돌려서 좀 더 간트차트같이 만들어보았습니다
- 워크스페이스 내 정보 카드가 더이상 위치 고정이 아닙니다 
- **TO-BE**
<br />
<br/>
<br/>
<br/>

feat:my-workdata 마이페이지 내 자료실 추가

---

Back-End/src/main/java/net/scit/backend/schedule/controller/ScheduleController.java
Front-End/bibim/vite/src/api/schedule.js
Front-End/bibim/vite/src/api/workspaceApi.js
Front-End/bibim/vite/src/views/schedule/components/ScheduleDetailModal.jsx
Front-End/bibim/vite/src/views/schedule/index.jsx
Front-End/bibim/vite/src/views/ws-select/components/CreateWorkspaceModal.jsx
Front-End/bibim/vite/src/views/ws-select/components/InviteWorkspace.jsx
Front-End/bibim/vite/src/views/ws-select/components/WorkspaceList.jsx

<br/>
feat/front_detail5 -> dev
<br/>
- **AS-IS**
- CSS 작업 등 프론트엔드 전반
- 상세모달 담당자변경 추가 
- **TO-BE**
<br />
<br/>
<br/>
<br/>

feat: 프론트 디테일

---

Back-End/src/main/java/net/scit/backend/member/listener/MemberEventListener.java
Front-End/bibim/vite/src/layout/MainLayout/Header/NotificationSection/index.jsx

<br/>
jasper -> dev
<br/>
- **AS-IS**
제목 참고
- **TO-BE**
<br />
<br/>
<br/>
<br/>

refactor: 개별 삭제 시 unreadCount 반영

---

Back-End/src/main/java/net/scit/backend/notification/controller/NotificationController.java

<br/>
<br/>
- **AS-IS**
- **TO-BE**
<br />
<br/>
<br/>
<br/>

refactor: 배포 dev 사이트에서의 SSE Error 테스트 해결책1

---

Back-End/src/main/java/net/scit/backend/notification/controller/NotificationController.java

<br/>
<br/>
- **AS-IS**
- **TO-BE**
<br />
<br/>
<br/>
<br/>

refactor: SSE 배포 사이트 에러 해결책2

---

Back-End/src/main/java/net/scit/backend/notification/controller/NotificationController.java
Back-End/src/main/java/net/scit/backend/notification/service/NotificationService.java
Back-End/src/main/java/net/scit/backend/notification/service/impl/NotificationServiceImpl.java

<br/>
<br/>
- **AS-IS**
- **TO-BE**
<br />
<br/>
<br/>
<br/>

refactor: SSE 오류 해결책3

---

Back-End/src/main/java/net/scit/backend/schedule/controller/ScheduleController.java
Front-End/bibim/vite/src/api/schedule.js
Front-End/bibim/vite/src/api/tag.js
Front-End/bibim/vite/src/views/schedule/components/KanbanBoard.jsx
Front-End/bibim/vite/src/views/schedule/components/ScheduleDetailModal.jsx
Front-End/bibim/vite/src/views/schedule/index.jsx

<br/>
feat/front_detail6 -> dev
<br/>
- **AS-IS**
- 일정관리 일정 상세 모달에서 상태 및 담당자 변경 기능 추가
- 일정관리 일정 상세 모달에서 자신의 스케줄이거나, 해당 워크스페이스 관리자일 때만 버튼 활성화 기능 추가
- 버튼 디자인 변경 
- **TO-BE**
<br />
<br/>
<br/>
<br/>

feat: 일정관리 등 프론트엔드 수정

---

Front-End/bibim/vite/src/views/dm/index.jsx
Front-End/bibim/vite/src/views/ws-channel/components/ChatComponent.css

<br/>
Fix/profile img-> dev
<br/>
- **AS-IS**
채널 프로필 사진 버그 수정
<br />

fix: 채널 프로필 사진 버그 수정

---

Back-End/src/main/java/net/scit/backend/notification/service/impl/NotificationServiceImpl.java
Front-End/bibim/vite/src/layout/MainLayout/Header/NotificationSection/index.jsx

<br/>
jasper-1st-debug-> dev
<br/>
- **AS-IS**
notification 내 serviceImpl의 sendNotification의 Emitter 수 지정
- **TO-BE**
<br />
<br/>
<br/>
<br/>

refactor: 모든 사람에게 알림이 갔다가 알림 아이콘 클릭 시 내 것만 보이는 오류 관련 1트

---

Back-End/src/main/java/net/scit/backend/channel/service/impl/ChannelServiceImpl.java
Back-End/src/main/java/net/scit/backend/dm/DTO/DmMessageDTO.java
Back-End/src/main/java/net/scit/backend/dm/controller/DMController.java
Back-End/src/main/java/net/scit/backend/dm/service/impl/DmServiceImpl.java

<br/>
Fix/dm channel-> dev
<br/>
- **AS-IS**
수정: 메세지를 보낼 시 프로필 이미지와 닉네임이 뜨지 않는 버그 수정
- **TO-BE**
<br />

fix: 채널/DM 프로필 버그 수정

---

Back-End/src/main/java/net/scit/backend/config/SecurityConfig.java
Back-End/src/main/java/net/scit/backend/notification/controller/NotificationController.java
Back-End/src/main/java/net/scit/backend/notification/service/impl/NotificationServiceImpl.java
Front-End/bibim/vite/src/layout/MainLayout/Header/NotificationSection/index.jsx

<br/>
2nd-debug -> dev
<br/>
- **AS-IS**
오류 잡기 관련 코드 추가
- **TO-BE**
<br />
<br/>
<br/>
<br/>

refactor: SSE 오류 잡기 2트

---

Front-End/bibim/vite/src/layout/MainLayout/Header/NotificationSection/index.jsx

<br/>
3rd-debug -> dev
<br/>
- **AS-IS**
unreadCount 즉시 반영되는 부분 추가
- **TO-BE**
<br />
<br/>
<br/>
<br/>

refactor: SSE 실시간 전송 오류 잡기 3트

---

Back-End/src/main/java/net/scit/backend/channel/service/impl/ChannelServiceImpl.java
Back-End/src/main/java/net/scit/backend/dm/service/impl/DmServiceImpl.java
Front-End/bibim/vite/src/views/ws-channel/components/ChatComponent.jsx

<br/>
Fix/dm channel bug-> dev
<br/>
- **AS-IS**
수정: 파일이나 이미지를 보낼 때 프로필 사진과 닉네임이 보이지 않는 것을 수정 하였습니다.

fix: 채널과 디엠 버그 수정

---

Back-End/src/main/java/net/scit/backend/channel/service/impl/ChannelServiceImpl.java

<br/>
fix/channel-bug-fix -> dev
<br/>
- **AS-IS**
빼먹은 부분 수정
- **TO-BE**
<br />

fix: 채널 bug fix

---

Front-End/bibim/vite/src/api/schedule.js
Front-End/bibim/vite/src/api/tag.js
Front-End/bibim/vite/src/views/pages/authentication/Login.jsx
Front-End/bibim/vite/src/views/schedule/components/Calendar.jsx
Front-End/bibim/vite/src/views/schedule/components/GanttChart.jsx
Front-End/bibim/vite/src/views/schedule/components/KanbanBoard.jsx
Front-End/bibim/vite/src/views/schedule/components/ScheduleDetailModal.jsx
Front-End/bibim/vite/src/views/schedule/components/TagEditModal.jsx
Front-End/bibim/vite/src/views/workdata/components/FileCardView.jsx
Front-End/bibim/vite/src/views/workdata/components/FileTable.jsx

<br/>
feat/front_detail7 -> dev
<br/>
- **AS-IS**
- 일정관리 태그 편집시 대분류태그 불러오기 및 수정 연결 (중분류, 소분류는 오늘 내 구현 예정)
- 일정관리 간트차트뷰 색깔 넣기 (대분류 색깔 받아옴)
- 일정관리 캘린더뷰 해당 일정 강조효과
- 자료실 테이블뷰, 카드뷰 디자인 살짝 수정
- **TO-BE**
<br />
<br/>
<br/>
<br/>

feat: 프론트 엔드 전반 기능 및 디자인 수정

---

Front-End/bibim/vite/src/api/mypage.js
Front-End/bibim/vite/src/views/mypage/component/MyCalendar.jsx
Front-End/bibim/vite/src/views/mypage/component/MyCalendarScheduleDetailModal.jsx
Front-End/bibim/vite/src/views/mypage/component/MyGanttChart.jsx
Front-End/bibim/vite/src/views/mypage/component/MyGanttScheduleDetailModal.jsx
Front-End/bibim/vite/src/views/mypage/component/MyScheduleDetailModal.jsx
Front-End/bibim/vite/src/views/mypage/component/MyWorkData.jsx
Front-End/bibim/vite/src/views/mypage/component/mySchedule.jsx
Front-End/bibim/vite/src/views/mypage/index.jsx

<br/>
ex) fix/mypage  -> dev
<br/>
- **AS-IS**
-  마이페이지 스케줄 워크스페이스 이미지 보이도록
- 워크스페이스 못 가져오던 문제 수정
- 워크스페이스별로 색깔 표시 (표시되는 파레트는 16가지 색으로 정해져있음. 16개 이하는 색 겹치지 않음. )
- 자료실 워크스페이스 이미지 넣음
- 간트차트 css 수정
- 
- **TO-BE**
<br />
<br/>
<br/>
<br/>

fix:mypage 마이페이지 스케줄&자료실 전반적 수정 (특히 이미지 관련) 

---

Front-End/bibim/vite/src/views/pages/auth-forms/AuthRegister.jsx

<br/>
ex) fix/css -> dev
<br/>
- **AS-IS**
- 회원가입 모달창 디자인 수정
- 프사 미리보기 부분 눌러도 이미지 등록으로 이동하도록. 
- 각 칸의 높이와 간격 조절
- 셀렉트창 글자 겹치는 문제 수정
- 비밀번호 조건 8글자 추가 
- **TO-BE**
<br />
<br/>
<br/>
<br/>

fix:css 회원가입 모달창 수정, 비밀번호 조건 추가

---

Back-End/src/main/java/net/scit/backend/channel/controller/ChatController.java
Back-End/src/main/java/net/scit/backend/channel/service/impl/ChannelServiceImpl.java
Back-End/src/main/java/net/scit/backend/dm/DTO/DmMessageDTO.java
Back-End/src/main/java/net/scit/backend/dm/controller/DMController.java
Back-End/src/main/java/net/scit/backend/dm/service/impl/DmServiceImpl.java
Front-End/bibim/vite/src/views/dm/index.jsx

왜되는지 모름 걍 됨 머리 아픔
<br/>
Fix/dm bug -> dev
<br/>
- **AS-IS**
몰라 왜되는지
<br />

fix: DM 파일 업로드 버그 수정

---

Front-End/bibim/vite/src/views/pages/authentication/LinkAccountModal.jsx

<br/>
ex) fix/css -> dev
<br/>
- **AS-IS**
- 구글 연동 모달창 수정
- **TO-BE**
<br />
<br/>
<br/>
<br/>

fix:css 구글 연동 모달창 디자인 수정 

---

Front-End/bibim/vite/src/views/schedule/components/Calendar.jsx
Front-End/bibim/vite/src/views/schedule/components/ScheduleCreateModal.jsx
Front-End/bibim/vite/src/views/schedule/components/ScheduleDetailModal.jsx
Front-End/bibim/vite/src/views/schedule/components/TagEditModal.jsx
Front-End/bibim/vite/src/views/schedule/index.jsx

<br/>
feat/front_detail10 -> dev
<br/>
- **AS-IS**
- 스케줄 생성 모달에서 생성시 변동사항 칸반보드 자동반영
- 스케줄 상세 모달에서 담당자 혹은 상태 변경시 칸반보드 자동반영
- **TO-BE**
<br />
<br/>
<br/>
<br/>

feat: 스케줄 생성 및 상세모달 변동사항 바로 칸반보드 반영

---

Front-End/bibim/vite/src/views/schedule/components/KanbanBoard.jsx

<br/>
<br/>
- **AS-IS**
- 칸반보드 번역 추가
- **TO-BE**
<br />
<br/>
<br/>
<br/>

feat: 칸반보드 번역 추가

---

Front-End/bibim/vite/src/api/channel.js
Front-End/bibim/vite/src/views/ws-channel/components/ChatComponent.jsx
Front-End/bibim/vite/src/views/ws-channel/components/ChatSummaryModal.jsx
Front-End/bibim/vite/src/views/ws-select/components/WorkspaceList.jsx

<br/>
feat/front_detail12 -> dev
<br/>
- **AS-IS**
- 채널 채팅 요약 기능 추가
- **TO-BE**
<br />
<br/>
<br/>
<br/>

feat: 채널 채팅 요약 기능 추가

---

Back-End/src/main/java/net/scit/backend/workspace/controller/WorkspaceController.java
Back-End/src/main/java/net/scit/backend/workspace/event/WorkspaceEvent.java
Back-End/src/main/java/net/scit/backend/workspace/service/WorkspaceService.java
Back-End/src/main/java/net/scit/backend/workspace/service/impl/WorkspaceServiceImpl.java

<br/>
<br/>
- **AS-IS**
워크스페이스 탈퇴 시 스케줄 담당자 일 때 발생하는 오류를 수정했습니다.
- **TO-BE**
워크스페이스에 혼자 남았을 때 스케줄 담당자일 때 워크스페이스 탈퇴가 안되는 현상을 수정해야합니다.
<br />
<br/>
<br/>
<br/>

refactor:workspace-withdrawal

---

Front-End/bibim/vite/src/views/schedule/components/TagCreateModal.jsx
Front-End/bibim/vite/src/views/schedule/components/TagEditModal.jsx
Front-End/bibim/vite/src/views/schedule/index.jsx
Front-End/bibim/vite/src/views/workdata/index.jsx
Front-End/bibim/vite/src/views/workdata_create/components/UploadStatusModal.jsx
Front-End/bibim/vite/src/views/workdata_create/index.jsx
Front-End/bibim/vite/src/views/ws-channel/components/ChannelCreateModal.jsx
Front-End/bibim/vite/src/views/ws-channel/components/ChannelEditModal.jsx

<br/>
ex) fix/css3-> dev
<br/>
- **AS-IS**
- 자료실 업로드 페이지 버튼 색 수정
- 일정 관리 상단에 자료실과 형식이 동일한 안내창 추가
- 태그 생성 및 관리에 스낵바 추가
- 채널 생성 및 수정 모달창 css 조정, 스낵바 추가 
- **TO-BE**
<br />
<br/>
<br/>
<br/>

fix/css3 자료실, 태그 관리, 채널 관리 모달창 css 변경 및 스낵바 추가 

---

Back-End/src/main/java/net/scit/backend/channel/service/impl/ChannelServiceImpl.java
Front-End/bibim/vite/src/views/ws-channel/components/ChatComponent.jsx

<br/>
<br/>
- **AS-IS**
수정: 프로필과 닉네임이 안뜨던거 수정
<br />

fix: 채널 버그 수정
